### ISSUE TITLE
React Example

### ISSUE THREAD

**Issue by pemrouz** [rijs/fullstack#19]
React Wizards, @leebyron @jkimbo @mere [re:this tweet](https://twitter.com/leeb/status/578091666201948160), does [this work](https://github.com/pemrouz/ripple-examples/blob/master/minimal-react/views/index.jade#L19-L21)? Chrome dev tools seem to confirm it's not doing a full rebuild.

I've changed it to use the more versatile imperative, asynchronous API to re-render when the data has changed:

```js
// declarative
<twitter-feed data="tweets" /> 

// imperative, synchronous
var tweets = ripple('tweets')

// imperative, asynchronous
ripple('tweets').on('response', function)
```

However, although this may have the performance benefit, it appears to me somewhat contrived as you would have to reinvoke the entire app on every data change, rather than a part of it (which isn't catastrophic I guess since React will only change what is required anyway). This seems to be because React does not like being invoked, but prefers to invoke - making it a framework, not a library. It would be pretty nice to see React [invert that control](http://martinfowler.com/bliki/InversionOfControl.html). (/cc @sebmarkbage @vjeux). But even with the current React paradigm, is there a more correct way to invoke a render of a particular subcomponent "from inside" React-land? Something like this perhaps?:

```js
...
componentDidMount: function() {
  ripple('tweets').on('response', () => { /* how to just re-render 'this'? */ })
}
...
```

**Comment by vjeux** [comment]
```
componentDidMount: function() {
  ripple('tweets').on('response', (tweets) => { this.setState({tweets: tweets}) })
}
```

**Comment by pemrouz** [comment]
Awesome, thanks @vjeux! The integration [looks much neater/idiomatic to me now](https://github.com/pemrouz/ripple-examples/blob/master/minimal-react/views/index.jade#L11-L19):

```js
getInitialState: function() {
  return { tweets: [] }
},
componentDidMount: function() {
  var self = this
  ripple('tweets').on('response', function() { 
    self.setState({ tweets: ripple('tweets') }) 
  })
},
```
