### ISSUE TITLE
Polyfill

### ISSUE THREAD

**Issue by pemrouz** [rijs/fullstack#22]
Dumping some thoughts here on polyfill strategy:

* I don't think Ripple does much that means we couldn't support old browsers if we actually tried - focus has just been on this being a playground to bring together the latest upcoming tech. 

* Ideally, we'd use something like the FT [cdn.polyfill.io](http://cdn.polyfill.io) to transparently polyfill backwards new technologies so we don't comprise the emphasis on using and exploring the latest standards. Anything new we develop should be contributed to such a service (serving selective polyfills based on user-agent).

* We need to look under the hood, as a lot polyfills do crazy things to work but may not be performant. I don't think we should use these ones and instead develop a simpler polyfill to support a smaller subset of browsers, or refactor the code to provide an easier downgrade path.

* The [webcomponents.js polyfill](https://github.com/WebComponents/webcomponentsjs) looks ok to use, however even before Web Components we implemented the simple `fn.call(<el>, data)` contract without it - we could fallback to that strategy if the polyfills are too hacky. [Giammarchi's IE8 polyfill for Custom Elements](http://webreflection.blogspot.co.uk/2015/03/bringing-custom-elements-to-ie8.html) is also quite interesting.

* There doesn't seem to be a decent O.o polyfill. Here are the options I can see:
  * There are too many limitations with [MaxArt2501/object-observe](https://github.com/MaxArt2501/object-observe) and [joelgriffith/object-observe-es5](https://github.com/joelgriffith/object-observe-es5), so potentially look into taking over [jdarling/Object.observe](https://github.com/jdarling/Object.observe) which needs a new maintainer.
  * Refactor the code to use [polymer/observe-js](https://github.com/polymer/observe-js)
  * Leverage the fact that we use `ripple('name')` to return a resource, so we could return a Proxy-like facade as discussed in several places.
  * Provide a less ambitious API that doesn't use O.o. I'm thinking this should just be in the form of exposing the underlying immutable objects (which should be done anyway at some point), rather than wrapping native functions to dispatch events. It would then be the responsibility of the user to dispatch change events. We would have to reconcile data differently though with this, as we currently only transfer diffs (in some cases).

* Ripple incentivises the Shadow DOM restriction to have scoped styles, as this makes components more cohesive and reusable. This will probably be an issue with any polyfill, but isn't unsurmountable. For example, if no Shadow DOM, we can have the `applycss` function reliably scope styles to an element by unique ID, or even better to the archetypal tag name (even if no Custom Elements present). The upgrade path for this will probably be easier once there is [declarative shadow root](https://lists.w3.org/Archives/Public/public-webapps/2015AprJun/0052.html).

Think that should be all, but there is still much R&D to do with things like ServiceWorkers which could still change things..

**Comment by pemrouz** [comment]
@addyosmani, do you have any advice/views with regards to which O.o polyfill to use?

**Comment by pemrouz** [comment]
@webreflection, did you have any luck with experimenting with the get/set solution for an O.o polyfill [mentioned here](https://esdiscuss.org/topic/object-observe-inital-polyfill)?

**Comment by WebReflection** [comment]
There's no way to polyfill `Object.observe` outside DOM land ( so no O.o for plain objects ) while in DOM land you might have similar behaviors via Custom Elements prototype and `attributeChangedCallback`

**Comment by WebReflection** [comment]
sorry for the rush: the TL;DR version is that get/set can wrap changes but not delete or new attributes so it would be a very broken polyfill without a Proxy. Cheers

**Comment by pemrouz** [comment]
@WebReflection, thanks, that makes sense. Well I guess Proxies would be a neat way to bring O.o to Firefox regardless (not sure if this has been done already?), but will probably need to think of something for IE too..

**Comment by WebReflection** [comment]
I once wrote this https://github.com/WebReflection/another-js#anotherjs-api ... works well in every browser since about ever, never went viral due not so fancy/magic taste (I guess)

If you need modifiers notifications at all cost, think about that approach, is similar IIRC to what Ember did with its basic objects.

**Comment by pemrouz** [comment]
@WebReflection thanks, will investigate!

**Comment by pemrouz** [comment]
No polyfill is necessary anymore
