### ISSUE TITLE
fix: replace socket.io

### ISSUE THREAD

**Issue by pemrouz** [rijs/fullstack#28]
- The entire framework is 5 kB, socket.io-client accounts for the other 50 kB. 
- [µWS](https://github.com/uWebSockets/uWebSockets) has some impressive performance stats

**Comment by 3liv** [comment]
Sounds interesting!
Does it compile on windows?
https://github.com/uWebSockets/uWebSockets/issues/207

**Comment by pemrouz** [comment]
Yeah, looks like some teething issues. Don't want to jump on this _too_ early as it can be quite messy for not much gain. Will probably wait to try it out after [this is completed](https://github.com/uWebSockets/uWebSockets/issues/233). Let me know if you find time to play around with it sooner..

**Comment by pemrouz** [comment]
socket.io replaced with uws (server) + nanosocket (client) in v8
